# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 32e08cbb8bee5293ff96e4701d02bd7e0f404933912eb2ec4cc3cd42a295f885806278a91e0501f656cfd67294caa0a1a2e03e46e512b584cbdea04c29b09d7d

test:
  secret_key_base: cd0e433ee8877540091984d96028aa6654b57336a1911f04aa8d5895d8d828ec1e3f8d5ead40d84fbe6eb34cf7c403da14c48ce432709de7d1c7e69ddf875942

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
